server:
  port: 9190
  timeout: 50
  uri-encoding: UTF-8

spring:
  datasource:
   name: test
   username: root
   password: 12345678
   drive-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8

mybatis:
  type-aliases-package: com.gaoqi.kitty.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
  mapper-locations: classpath:mapping/*Mapper.xml

